#!/usr/bin/env bash
# Install Nginx on a web server to specifications
sudo  apt -y update
sudo apt -y install nginx
sudo chown -R $USER:$USER /var/www
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
service nginx start
