#!/usr/bin/env bash
# Configure Nginx server to redirect to another page.

sudo apt-get update -y
sudo apt-get install -y nginx
sudo chown -R "$USER":"$USER" /var/www
echo "Hello World!" > /var/www/html/index.html
sudo sed -i "/server_name _;/a rewrite /redirect_me https://www.linkedin.com permanent;" /etc/nginx/sites-enabled/default
sudo nginx -s reload
