#!/usr/bin/env bash
# Configure Nginx server to redirect to another page and custom 404 page.

sudo apt-get update -y
sudo apt-get install -y nginx

sudo sh -c echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://www.linkedin.com/in/oluwafemi-awodele permanent;" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" > /usr/share/nginx/html/page_error_404.html
sudo sed -i '37i error_page 404 /page_error_404.html;\nlocation = /page_error_404.html {\nroot /usr/share/nginx/html; \ninternal;\n}\n' /etc/nginx/sites-enabled/default

sudo service nginx restart
