#!/usr/bin/env bash
# Install Nginx on a web server to specifications
sudo  apt-get -y update
sudo apt-get -y install nginx
sudo chown -R $USER:$USER /var/www
touch /var/www/html/index.html
mkdir -p /var/www/error
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
server_config=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	
	server_name _;
	
	add_header X-Served-By $hostname;
	
	location / {
		try_files \$uri \$uri/ =404;
	}
	
	if (\$request_filename ~ redirect_me){
		rewrite ^ https://youtube.com permanent;
	}
	
	error_page 404 /404.html;
	
	location = /404.html {
		internal;
	}
}"

sudo echo "$server_config" > /etc/nginx/sites-available/default
sudo service nginx restart
