#!/usr/bin/env bash
#Bash script that displays numbers from 1 to 20
N=1
while [ $N -le 20 ]; do
	echo "$N"
	case "$N" in
		4)
			echo "bad luck from China";;
		9)
			echo "bad luck from Japan";;
		17)
			echo "bad luck from Italy";;
	esac
	(( N=N+1 ))
done
