#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes
H=0
while [ $H -le 12 ]; do
	M=1
	echo "Hour: $H"
	while [ $M -le 59 ]; do
		echo "$M"
		(( M=M+1))
	done
	(( H=H+1 ))
done
